//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AdminUser
    {
        public int AdminID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string PermissionString { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string AdminUserName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Flag1 { get; set; }
        public Nullable<int> Flag2 { get; set; }
        public Nullable<int> Flag3 { get; set; }
        public Nullable<int> Flag4 { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
