//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_AutoShipDetail
    {
        public int ID { get; set; }
        public int AutoShipID { get; set; }
        public int ItemID { get; set; }
        public string ItemTitle { get; set; }
        public string ProductCode { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> PriceLevel { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> ExtPrice { get; set; }
        public Nullable<decimal> TaxableAmount { get; set; }
        public Nullable<decimal> ShippingValue { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
