//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Categories
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> CategoryGroupID { get; set; }
        public Nullable<int> CategoryLevel { get; set; }
        public string CategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string CategoryImage { get; set; }
        public int SeqNo { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
