//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_CommissionDetail
    {
        public int CDID { get; set; }
        public int CustID { get; set; }
        public int CommissionID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<int> PeriodQualificationLevel { get; set; }
        public Nullable<int> VolumeID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<decimal> VolumeTotal { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> AutoOptionID { get; set; }
        public string Eligible { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
        public string Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        public Nullable<int> OverrideByID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> PayoutID { get; set; }
    }
}
