//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Commissions
    {
        public int CommissionID { get; set; }
        public string CommissionName { get; set; }
        public string CommissionDesc { get; set; }
        public Nullable<int> PeriodTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LastPeriodProcessed { get; set; }
        public Nullable<int> LastPeriodToBucket { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
