//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EmailFormSubmitLog
    {
        public int EmailID { get; set; }
        public int UserID { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public short StatusID { get; set; }
        public System.DateTime Postdate { get; set; }
    }
}
