//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EmailTemplates
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> SendInterval { get; set; }
        public Nullable<int> Frequency { get; set; }
        public string RulesDescription { get; set; }
        public string StoredProcedure { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
