//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_EventDetail
    {
        public int ID { get; set; }
        public Nullable<int> EventID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Instructions { get; set; }
        public string DataLabel { get; set; }
        public Nullable<int> IsRequired { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
