//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Fees
    {
        public int ID { get; set; }
        public int FeeID { get; set; }
        public Nullable<int> FeeTypeID { get; set; }
        public string FeeTitle { get; set; }
        public string Description { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
