//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FormSubmitLog
    {
        public int ID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string FormType { get; set; }
        public string MsgTextBlock { get; set; }
        public string FormResult { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
