//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ImportPayoutTransactions
    {
        public int ID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> PayoutID { get; set; }
        public string CommissionDetailID { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string AccountingID { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> TotalPaymentAmount { get; set; }
        public string PayeeName { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
