//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ImportDataLogDetail
    {
        public int RID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string TableLabel { get; set; }
        public Nullable<int> UID { get; set; }
        public string RecordContent { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
