//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Item
    {
        public int ItemID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string ProductCode { get; set; }
        public string ItemName { get; set; }
        public string ItemTitle { get; set; }
        public string ItemDescription { get; set; }
        public string ItemImage1 { get; set; }
        public string ItemImage2 { get; set; }
        public string ItemDetailPage { get; set; }
        public string ItemVideo { get; set; }
        public Nullable<int> IsShip { get; set; }
        public int MinQuantity { get; set; }
        public int MaxQuantity { get; set; }
        public Nullable<int> ToItemID { get; set; }
        public Nullable<int> FromItemID { get; set; }
        public string Status { get; set; }
        public string isAutoShip { get; set; }
        public Nullable<byte> isShipping { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<byte> IsPrePackaged { get; set; }
        public Nullable<byte> DisplayFlag { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int ProgramID { get; set; }
        public string GLCode { get; set; }
    }
}
