//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ItemVendors
    {
        public int ISID { get; set; }
        public int ItemID { get; set; }
        public string ServiceProvider { get; set; }
        public string ServiceProviderNotes { get; set; }
        public string Location { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
