//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ItemPromotion
    {
        public int ID { get; set; }
        public int PromotionID { get; set; }
        public int ItemID { get; set; }
        public string PromotionTitle { get; set; }
        public string PromotionDescription { get; set; }
        public int PricingType { get; set; }
        public int FreePeriod { get; set; }
        public Nullable<decimal> PromotionAmount { get; set; }
        public int PromotionPeriod { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
