//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OrderHistory
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string Description { get; set; }
        public decimal ChangeAmount { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public decimal BalanceChangeAmount { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public int ExportBatchID { get; set; }
        public string ExportStatus { get; set; }
        public string GLCode { get; set; }
        public string GLAccount { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
