//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_OrderHeader
    {
        public Nullable<int> ID { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> TmpORderID { get; set; }
        public int CustID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> CustType { get; set; }
        public Nullable<int> PriceLevel { get; set; }
        public string OrderType { get; set; }
        public Nullable<int> OfferID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string ShipFirstName { get; set; }
        public string ShipLastName { get; set; }
        public string SHipName { get; set; }
        public string ShipAddress1 { get; set; }
        public string ShipAddress2 { get; set; }
        public string ShipCity { get; set; }
        public string SHipCounty { get; set; }
        public string ShipState { get; set; }
        public string SHipPostalCode { get; set; }
        public string ShipCountry { get; set; }
        public string ShipPhone { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> RetailTotal { get; set; }
        public Nullable<decimal> SaleTotal { get; set; }
        public Nullable<decimal> TaxableTotal { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> FulFillmentBatchID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> TriggerDate { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ShipMethod { get; set; }
        public string Shipper { get; set; }
        public string TrackingNumber { get; set; }
        public string ShippingSignedOff { get; set; }
        public string DataValue1 { get; set; }
        public string Status { get; set; }
        public Nullable<int> OriginalOrderID { get; set; }
        public Nullable<int> AutoShipID { get; set; }
        public Nullable<System.DateTime> CommissionDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<int> StatementID { get; set; }
        public string VariantData1 { get; set; }
        public string SentToProcessing { get; set; }
        public string SentToSynchronize { get; set; }
        public Nullable<int> AdminID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
        public System.DateTime Change_Date { get; set; }
        public Nullable<decimal> CancelTotal { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
