//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PayOut
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public string RefNumber { get; set; }
        public Nullable<decimal> PayoutAmount { get; set; }
        public Nullable<System.DateTime> PayoutDate { get; set; }
        public Nullable<byte> PayoutMethodID { get; set; }
        public Nullable<byte> PayoutTypeID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<byte> PayoutStatusID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string SentToProcessing { get; set; }
        public string VariantData1 { get; set; }
        public Nullable<int> PayoutCounter { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string SentToProcessingID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> CheckNumber { get; set; }
    }
}
