//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Periods
    {
        public int PID { get; set; }
        public int PeriodID { get; set; }
        public Nullable<int> PeriodTypeID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> PeriodStatusID { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string PeriodName { get; set; }
    }
}
