//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Ranks
    {
        public int RankID { get; set; }
        public string RankAbbreviation { get; set; }
        public string RankTitle { get; set; }
        public string Description { get; set; }
        public string RulesDescription { get; set; }
        public Nullable<int> RankTypeID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> LastPeriodProcessed { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
