//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_StatementLog
    {
        public int LogID { get; set; }
        public Nullable<int> StatementID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> adminid { get; set; }
        public string Status { get; set; }
    }
}
