//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_StatementHeader
    {
        public int StatementID { get; set; }
        public string StatementType { get; set; }
        public Nullable<int> StatementTypeID { get; set; }
        public Nullable<int> CustID { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public Nullable<int> AdminID { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> Postdate { get; set; }
        public Nullable<decimal> StatementTotal { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
    }
}
