//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_StockBin
    {
        public int InventoryID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public string ProductCode { get; set; }
        public string LotID { get; set; }
        public Nullable<decimal> LotCost { get; set; }
        public string Vendor { get; set; }
        public Nullable<System.DateTime> LotReceiptDate { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> OnHand { get; set; }
        public Nullable<decimal> QtyCommitted { get; set; }
        public Nullable<decimal> QtyShipped { get; set; }
        public Nullable<decimal> Available { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
