//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_StatusLog
    {
        public int CSID { get; set; }
        public int CustID { get; set; }
        public string PropertyLabel { get; set; }
        public int OldValue { get; set; }
        public int NewValue { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string Comments { get; set; }
        public System.DateTime PostDate { get; set; }
        public string ChangeBy { get; set; }
    }
}
