//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TreeLog
    {
        public int ID { get; set; }
        public int CustID { get; set; }
        public int UplineID { get; set; }
        public int NewUplineID { get; set; }
        public int ChangeBy { get; set; }
        public Nullable<short> TreeID { get; set; }
        public System.DateTime ChangeDate { get; set; }
    }
}
