//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Tree
    {
        public int ConnectID { get; set; }
        public int TreeID { get; set; }
        public int CustID { get; set; }
        public int UplineID { get; set; }
        public Nullable<int> OriginalUplineID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> CustTypeID { get; set; }
        public Nullable<int> QualStatID { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Commission { get; set; }
        public Nullable<int> DownCount { get; set; }
        public Nullable<int> DowncountAdjusted { get; set; }
        public Nullable<int> Flag1 { get; set; }
        public Nullable<int> Flag2 { get; set; }
        public Nullable<int> LegID { get; set; }
        public string VariantData1 { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
