//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VendorRebateTransactions
    {
        public int ID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> VolumeID { get; set; }
        public string RebateType { get; set; }
        public int CustID { get; set; }
        public string SecID { get; set; }
        public string VendorPayeeID { get; set; }
        public string PayeeName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> SalesStartDate { get; set; }
        public Nullable<System.DateTime> SalesEndDate { get; set; }
        public Nullable<decimal> TotalSalesAmount { get; set; }
        public Nullable<decimal> MemberQualifiedAmount { get; set; }
        public Nullable<decimal> MemberRebateAmount { get; set; }
        public Nullable<decimal> CorporateQualifiedAmount { get; set; }
        public Nullable<decimal> CorporateRebateAmount { get; set; }
        public string VariantData1 { get; set; }
        public string VariantData2 { get; set; }
        public Nullable<int> Flag1 { get; set; }
        public Nullable<int> Flag2 { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public string SecStatus { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> parentid { get; set; }
    }
}
