//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VolumeHeader
    {
        public int ID { get; set; }
        public Nullable<int> VolumeID { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public Nullable<decimal> VOLUMETOTAL { get; set; }
        public Nullable<decimal> AdjustedTotal { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<int> OverrideByID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<int> AdminID { get; set; }
        public Nullable<int> BatchID { get; set; }
    }
}
