//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VolumeItem
    {
        public int IVID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> periodTypeID { get; set; }
        public Nullable<int> PricingLevel { get; set; }
        public Nullable<int> LevelID { get; set; }
        public int VolumeID { get; set; }
        public int VolumeType { get; set; }
        public Nullable<int> TreeID { get; set; }
        public Nullable<decimal> VolumeAmount { get; set; }
        public Nullable<decimal> VolumePercent { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
    }
}
