//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_VolumeDetail
    {
        public int EntryID { get; set; }
        public int CustID { get; set; }
        public Nullable<int> VolumeID { get; set; }
        public int TreeID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public string SourceName { get; set; }
        public System.DateTime SourceDate { get; set; }
        public Nullable<decimal> VolumeTotal { get; set; }
        public Nullable<decimal> VolumeAdj { get; set; }
        public string VolumeStatus { get; set; }
        public Nullable<int> CommissionDetailID { get; set; }
        public Nullable<int> PeriodID { get; set; }
        public string Status { get; set; }
        public System.DateTime StatusDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> AdminID { get; set; }
        public System.DateTime PostDate { get; set; }
        public Nullable<int> OverrideByID { get; set; }
        public Nullable<int> BatchID { get; set; }
        public string SourceDescription { get; set; }
    }
}
