//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Volumes
    {
        public int VolumeID { get; set; }
        public string VolumeName { get; set; }
        public string VolumeDesc { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PeriodTypeID { get; set; }
        public Nullable<int> LastPeriodProcessed { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int VolumeType { get; set; }
        public Nullable<int> CustID { get; set; }
    }
}
