//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTrack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpOrderHeaderForPayment
    {
        public int CustID { get; set; }
        public int OrderID { get; set; }
        public string Name { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<decimal> SaleTotal { get; set; }
        public Nullable<decimal> RetailTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Paid { get; set; }
        public Nullable<decimal> BalanceDue { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public string Status { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PostDate { get; set; }
    }
}
